# Global settings.
Global:
  # Broadcast to everyone when a player is muted or unmuted.
  Notify: true
  # Default mute time in minutes when not specified in mute command. (52594900 = perm)
  DefaultTime: 5
  # Maximum mute time
  MaxTime: 
  # Allow admins to see the muted messages
  AdminListen: false
  # Default mute reason
  DefaultReason: None
  # Permission node for admins when AdminListen is enabled
  BroadcastNode: mutemanager.listen
  # Block optional commands when muted
  BlockCommands: false
  # Commands that are blocked when a player is muted
  Commands:
    - /msg
    - /tell
  AllowOfflineMute: false
  # Nothing to see here
  Debug: false
# Message templates. The following tokens are supported.
# %DURATION% - Length of the mute
# %REASON% - Reason for the mute
# %DURATIONTEXT%
# %REASONTEXT%
# %AUTHOR% - Name of the muter
# %PLAYER% - Name of the muted player
Messages:
  NoPermission: '&cYou do not have permission to use this command!'
  ZeroSeconds: 0 seconds
  Minutes: minutes
  Seconds: seconds
  Hours: hours
  Days: days
  Years: years
  Forever: forever
  UnableToUnMute: '&eUnable to unmute &b%PLAYER%&e.'
  # %REASONTEXT%
  Reason: '&eReason: &a%REASON%'
  # %DURATIONTEXT%
  Duration: '&eDuration: &a%DURATION%'
  YouHaveBeenMuted: '&eYou have been muted! %DURATIONTEXT% %REASONTEXT%'
  YouHaveBeenUnMuted: '&eYou have been unmuted!'
  NoPlayer: 'There is no player by that name online!'
  PlayerNowMuted: '&b%PLAYER% &eis now muted! %DURATIONTEXT% %REASONTEXT%'
  PlayerNowUnMuted: '&b%PLAYER% &ehas been unmuted!'
  YouAreMuted: '&eYou are muted! %DURATIONTEXT% %REASONTEXT%'
  MaxReason: 'Mute time of &a%TIME% &rminutes exceeds maximum &a%MAX% &rminutes!'
  Exempt: '&b%PLAYER% &eis exempt from mute!'
Database:
  Enabled: false
  User: USERNAME
  Pass: PASSWORD
  Url: jdbc:mysql://localhost/mutemanager
  Driver: com.mysql.jdbc.Driver
